// SPDX-License-Identifier: GPL-3.0-or-later
// KentOSCad — ai: the two generated documents a model reads before it starts.
//
// WHY A DOCUMENT WHEN THERE IS ALREADY A SCHEMA. Every typed parameter is
// already machine-readable through `inputSchema`, so copying three hundred
// signatures into prose would buy nothing and rot in a week. `llms.txt` earns its
// place by carrying exactly what JSON Schema cannot say:
//
//   * the unit — `Mm`, int64 fixed-point millimetres, never a float;
//   * the frame and the axis naming — `Sağa (Y)` is easting, `Yukarı (X)` is
//     northing, and easting is written first (model.md R37a);
//   * the Turkish naming and folding convention, so a model knows `GIZLE`,
//     `gizle` and `GİZLE` are one word;
//   * the approval model — a write does not happen when it is called;
//   * the handle rule — where a coordinate may come from;
//   * the order the tools are meant to be used in.
//
// Both files are GENERATED by `kentos_docgen` and never hand-edited (CLAUDE.md
// 5.20), regenerated in the same commit as any registry change (6.14), and
// checked by `scripts/ci-gate-docs.sh`.
#pragma once

#include "kentos_cad/ai/tool.hpp"

#include "kentos_cad/command/registry.hpp"

#include <string>

namespace kentos::ai {

/// The rules of the house, in Turkish: the unit, the axis names, Turkish
/// folding, the handle rule, the approval rule, and the order to call the read
/// tools in.
///
/// SHARED WITH THE CHAT'S SYSTEM PROMPT ON PURPOSE. `docs/llms.txt` opens with
/// this text and `app::ChatPanel` sends it as the system message, so an outside
/// agent reading the file and the model inside the program are told the same
/// rules in the same words. Two copies of these paragraphs would be two
/// different programs to learn (CLAUDE.md 5.20, 5.10 in spirit).
std::string agent_preamble();

/// The index: what this program is, the rules that govern using it, and links to
/// the manual. Markdown, in the llmstxt.org shape (one H1, a blockquote summary,
/// then H2 sections of links).
std::string llms_txt(const command::Registry& registry);

/// The same index followed by every tool's name, summary and parameters — the
/// de-facto `llms-full.txt`, for a client that would rather read one file than
/// call `tools/list`.
std::string llms_full_txt(const command::Registry& registry);

/// The first line both files carry, so a hand edit is visible at a glance.
constexpr const char* kGeneratedNotice =
    "<!-- ÜRETİLMİŞ DOSYA — elle düzenlemeyin. Kaynak: komut kataloğu (Registry). "
    "Yeniden üretmek için: make reference -->";

} // namespace kentos::ai
